# permissions for end users to view backuppolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: bastion
    app.kubernetes.io/managed-by: kustomize
  name: backuppolicy-viewer-role
rules:
- apiGroups:
  - bastion.io
  resources:
  - backuppolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bastion.io
  resources:
  - backuppolicies/status
  verbs:
  - get
