# permissions for end users to edit restores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: bastion
    app.kubernetes.io/managed-by: kustomize
  name: restore-editor-role
rules:
- apiGroups:
  - bastion.io
  resources:
  - restores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bastion.io
  resources:
  - restores/status
  verbs:
  - get
