---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - bastion.io
  resources:
  - backuppolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bastion.io
  resources:
  - backuppolicies/finalizers
  verbs:
  - update
- apiGroups:
  - bastion.io
  resources:
  - backuppolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bastion.io
  resources:
  - restores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bastion.io
  resources:
  - restores/finalizers
  verbs:
  - update
- apiGroups:
  - bastion.io
  resources:
  - restores/status
  verbs:
  - get
  - patch
  - update
