apiVersion: apps/v1
kind: Deployment
metadata:
  name: bastion-backup
  namespace: bastion-system
  labels:
    app: bastion-backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bastion-backup
  template:
    metadata:
      labels:
        app: bastion-backup
    spec:
      serviceAccountName: bastion-backup-sa
      containers:
        - name: bastion-backup
          image: bastion:latest
          imagePullPolicy: Never
          args:
            - --backup-root=/backups
            - --max-retries=5
            - --gc-retain=10m
          volumeMounts:
            - name: backup-storage
              mountPath: /backups
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

        - name: custom-api-server
          image: bastion-apiserver:latest
          imagePullPolicy: Never
          args:
            - --backup-root=/backups
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: certs
              mountPath: /certs
              readOnly: true
            - name: backup-storage
              mountPath: /backups
      volumes:
        - name: certs
          secret:
            secretName: api-server-tls
        - name: backup-storage
          persistentVolumeClaim:
            claimName: bastion-backup-pvc
