apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bastion-backup-pvc
  namespace: bastion-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
