apiVersion: v1
kind: PersistentVolume
metadata:
  name: bastion-backup-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/shashipriya06/bastion-backups 
  storageClassName: manual  # Important: prevents dynamic provisioning
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bastion-backup-pvc
  namespace: bastion-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
