apiVersion: v1
kind: ServiceAccount
metadata:
  name: bastion-backup-sa
  namespace: bastion-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bastion-backup-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bastion-backup-rolebinding
subjects:
  - kind: ServiceAccount
    name: bastion-backup-sa
    namespace: bastion-system
roleRef:
  kind: ClusterRole
  name: bastion-backup-role
  apiGroup: rbac.authorization.k8s.io
