apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: bastion-backup
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --backup-root={{ .Values.backupRoot }}
            - --max-retries={{ .Values.maxRetries }}
            - --gc-retain={{ .Values.gcRetain }}
          volumeMounts:
            - name: backup-storage
              mountPath: {{ .Values.backupRoot }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: backup-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
