name: Bastion CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      go-cache-key: ${{ steps.cache-go.outputs.cache-hit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'  # your Go version

      - name: Cache Go modules
        id: cache-go
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  golangci-lint:
    name: Run Go Linter
    needs: prepare
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Restore Go modules cache
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.57.2
          golangci-lint --version

      - name: Run golangci-lint (exclude tests)
        run: |
          golangci-lint run ./... \
          --skip-dirs-use-default \
          --skip-dirs 'test' \
          --skip-dirs 'tests' \
          --skip-dirs '.*test.*' \
          --skip-files '.*_test.go'


  bdd:
    name: Run BDD Tests
    needs: [golangci-lint]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Restore Go modules cache
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Create KinD cluster
        run: |
          kind create cluster --wait 60s

      - name: Set up KUBECONFIG
        run: |
          echo "KUBECONFIG=${HOME}/.kube/config" >> $GITHUB_ENV

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install CRDs
        run: |
          kubectl apply -f test/data/

      - name: Run Tests
        run: |
          go test ./internal/controllers/... -v --ginkgo.v --ginkgo.fail-fast --ginkgo.timeout=10m

      - name: Delete KinD cluster
        if: always()
        run: kind delete cluster
