name: Bastion Backup Controller CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'  # or 1.22 if you prefer
          cache: true

      - name: Install controller-gen
        run: |
          go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.14.0

      - name: Install Envtest Binaries
        run: |
          go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
          setup-envtest use -p env 1.30.x >> $GITHUB_ENV

      - name: Print KUBEBUILDER_ASSETS
        run: |
         echo "Assets: $KUBEBUILDER_ASSETS"

      - name: Cache Go Modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Debug Env
        run: env | grep KUBEBUILDER

      - name: Run BDD Tests
        run: |
          go test ./internal/controllers/... -v --ginkgo.v --ginkgo.progress --ginkgo.fail-fast --ginkgo.timeout=10m

      - name: Build the Bastion Controller
        run: |
          go build -v ./cmd/main.go
